# Generated by Django 3.0.4 on 2020-04-26 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='created time')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='changed time')),
                ('title', models.CharField(help_text='Title', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Contains')),
                ('is_online', models.BooleanField(default=True, help_text='Is/not the topic online?')),
                ('user', models.ForeignKey(help_text='Associated user table', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='created time')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='changed time')),
                ('content', models.CharField(help_text='The talks', max_length=255)),
                ('up', models.IntegerField(default=0, help_text='support')),
                ('down', models.IntegerField(default=0, help_text='against')),
                ('topic', models.ForeignKey(help_text='Associated topic table', on_delete=django.db.models.deletion.CASCADE, to='post.Topic')),
            ],
            options={
                'ordering': ['-created_time'],
                'abstract': False,
            },
        ),
    ]
